title: Growing Tomorrow
description: A libary of data schemas related to soil health
theme: just-the-docs

url: https://agrifooddatacanada.github.io/GrowingTomorrowSoilHealth/

aux_links:
  Template Repository: https://github.com/agrifooddatacanada/GrowingTomorrowSoilHealth
